### ISSUE TITLE
Changement sur les actualités de la home

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/vigo-postgrowth-lab#2]
<img width="1792" alt="Capture d’écran 2024-03-18 à 17 32 46" src="https://github.com/osunyorg/vigo-postgrowth-lab/assets/2088968/3090033c-11b0-47df-b23d-307d90f6beeb">

Il faudrait libérer la colonne de gauche, comme au-dessus.
@Clararigaud dis-moi si pas clair ;)

**Comment by Clararigaud** [comment]
En fait il était repassé en mode liste je ne sais pas pourquoi ? C'est voulu ? En carousel la colonne est libérée par défaut

**Comment by Clararigaud** [comment]
done
